### PR TITLE
ContinueOnError bug

### LINKED ISSUE #6: ContinueOnError logic bug
[This commit](https://github.com/cake-build/frosting/commit/bec159166897674926b0302da3048abf91a58e3f) adding `ContinueOnError` support  bases the logic on the presence of `TaskNameAttribute` instead of `ContinueOnErrorAttribute`.

The test passes since the `ContinueOnErrorTask` is also decorated with a `TaskNameAttribute`.

### PR DESCRIPTION
**Pull request by mderriey**
Closes #6.

### CODE REVIEW

**Comment by patriksvensson** [comment]
Ouch! This is embarrassing! Thanks for finding this!

**Comment by patriksvensson** [comment]
Could you squash the commits to a single one and I'll merge it ASAP!

**Comment by mderriey** [comment]
Not that I don't want to do it, but you can now [do it when merging the PR](https://github.com/blog/2141-squash-your-commits).

If you're not comfortable doing it, I'll squash on my end.

**Comment by patriksvensson** [comment]
I'm on my phone at the moment so if you could squash it would be perfect :smile:

**Comment by gep13** [comment]
@mderriey although that button will squash the commit, it no longer uses `--no-ff`, which is one thing that we like about the current process that we follow for all the Cake Repos.  If that button, was squash, and merge with no fast forward, then I think we would use it all the time.

**Comment by mderriey** [comment]
no worries. I've just squashed the commits and updated the source branch.

**Comment by mderriey** [comment]
out of curiosity, any idea why the AppVeyor build fails? Do you have the MyGet API key only available to the `develop` branch somehow?

**Comment by gep13** [comment]
@mderriey Environment Variables in AppVeyor are not "hydrated" for Pull Request builds, as a result, the MyGet API Key is not aviailable.  We need to update the build script to only push to MyGet when on develop or master branch.

I think this is the first PR into this repo, so the first time we have seen it :-)

**Comment by patriksvensson** [comment]
@mderriey Merged! Thank you for your contribution! Much appreciated! :+1:

**Pull request merged**
